{"stats": {"errors": 0, "failures": 1, "passes": 0, "skipped": 0, "encoding": "UTF-8", "total": 1}, "results": [{"classname": "index_test:HelperTest", "name": "test_bytes", "time": 0.0002503395080566406, "type": "failure", "errtype": "builtins.AssertionError", "message": "'hello world' != None", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/pb-tester-ccdle12/python-primer-jsong-pb-sf-072618/test/index_test.py\", line 10, in test_bytes\n    self.assertEqual(s, bytes_to_str(b))\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 829, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 822, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: 'hello world' != None\n"}]}